#!/bin/sh

userresources="${XDG_CONFIG_HOME:-$HOME/.config}/X11/xresources"
# usermodmap="${XDG_CONFIG_HOME:-$HOME/.config}/X11/xmodmap"
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
	xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
	xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
	xrdb -merge "$userresources"
fi

# fcitx5 will overwrite xmodmap and load .Xmodmap instead.
# if [ -f "$usermodmap" ]; then
# 	xmodmap "$usermodmap"
# fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/X11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/X11/xprofile"
else
	. "$HOME/.xprofile"
fi

WM="dwm"
if [ -x "${XDG_CONFIG_HOME:-$HOME/.config}/X11/xexec" ]; then
	exec "${XDG_CONFIG_HOME:-$HOME/.config}/X11/xexec" "$WM" "$X11_SV_DIR"
else
	exec "$WM"
fi
