"" TODO add start plugin: vim-devicons, vim-startify;
""	add keybindings for NERDTree. 

"" Gernal setting
set nocompatible
set number relativenumber
set clipboard=unnamedplus
set encoding=utf-8
set mouse=a
set scrolloff=5
set noshowmode
syntax on

"" Start plug-ins setting
let g:airline_powerline_fonts = 1
