#!/usr/bin/sh

# profile file. Runs on login. Environmental variables are set here.

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export WINEPREFIX="${XDG_DATA_HOME:-$HOME/.local/share}/wineprefixes/default"
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export GTK_RC_FILES="$XDG_CONFIG_HOME"/gtk-1.0/gtkrc
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export GOPATH="$XDG_DATA_HOME"/go
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
export TEXMACS_HOME_PATH=$XDG_STATE_HOME/texmacs
export OCTAVE_HISTFILE="$XDG_CACHE_HOME/octave-hsts"
export OCTAVE_SITE_INITFILE="$XDG_CONFIG_HOME/octave/octaverc"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
export M_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=\@im=fcitx
export QT_QPA_PLATFORMTHEME=qt5ct

export PATH="$PATH:$HOME/.local/bin:$HOME/.local/bin/statusbar"

export EDITOR="vim"
export TERMINAL="alacritty"
export BROWSER="firefox"

if [ -s "${XDG_CONFIG_HOME:-$HOME/.config}/bash/bashrc" ]; then
    . "${XDG_CONFIG_HOME:-$HOME/.config}/bash/bashrc"
fi

if [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
    exec startx
fi
