[a-general]
# Press Ctrl-H to access it
home = "gemini://gemini.circumlunar.space"

auto_redirect = false

http = 'default'
search = "gemini://geminispace.info/search"

color = true

ansi = true

bullets = true

show_link = false

left_margin = 0.15

max_width = 100

downloads = ''

page_max_size = 2097152  # 2 MiB
page_max_time = 10

scrollbar = "auto"
underline = true


[auth]
# Authentication settings
# Note the use of single quotes for values, so that backslashes will not be escaped.

[auth.certs]
# Client certificates
# Set domain name equal to path to client cert
# "example.com" = 'mycert.crt'

[auth.keys]
# Client certificate keys
# Set domain name equal to path to key for the client cert above
# "example.com" = 'mycert.key'


[keybindings]
bind_tab1 = "!"
bind_tab2 = "@"
bind_tab3 = "#"
bind_tab4 = "$"
bind_tab5 = "%"
bind_tab6 = "^"
bind_tab7 = "&"
bind_tab8 = "*"
bind_tab9 = "("
bind_tab0 = ")"

bind_bottom = "o"
bind_edit = "e"

bind_link1 = "1"
bind_link2 = "2"
bind_link3 = "3"
bind_link4 = "4"
bind_link5 = "5"
bind_link6 = "6"
bind_link7 = "7"
bind_link8 = "8"
bind_link9 = "9"
bind_link0 = "0"

# All keybindings:
#
# bind_bottom
# bind_edit
# bind_home
# bind_bookmarks
# bind_add_bookmark
# bind_save
# bind_reload
# bind_back
# bind_forward
# bind_moveup
# bind_movedown
# bind_moveleft
# bind_moveright
# bind_pgup
# bind_pgdn
# bind_new_tab
# bind_close_tab
# bind_next_tab
# bind_prev_tab
# bind_quit
# bind_help
# bind_sub: for viewing the subscriptions page
# bind_add_sub
# bind_copy_page_url
# bind_copy_target_url
# bind_beginning: moving to beginning of page (top left)
# bind_end: same but the for the end (bottom left)

[url-handlers]
other = 'default'

[cache]

max_size = 0  # Size in bytes
max_pages = 30 # The maximum number of pages the cache will store

timeout = 1800 # 30 mins

[proxies]


[subscriptions]
popup = true

update_interval = 1800 # 30 mins

workers = 3

entries_per_page = 20


[theme]
bottombar_label = "#fabd2f"
bottombar_bg = "#928374"
scrollbar = "gray"
