#!/usr/bin/bash
# add following lines to /etc/bash.bashrc or it wont' work when you open an
# interactive shell inside a session.
# if [ -s "${XDG_CONFIG_HOME:-$HOME/.config}/bash/bashrc" ]; then
    # . "${XDG_CONFIG_HOME:-$HOME/.config}/bash/bashrc"
# fi

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# PS1='[\u@\h \W]\$ '
export PS1="╭── [\u on \h] in [$0 - \W]\n╰─> "

# load my aliases
source "$HOME/.config/shell/aliasrc"

## set keybindings to vi mode.
set -o vi
