#!/bin/sh
# vim: filetype=sh
# profile file. Runs on login. Environmental variables are set here.

# set XDG base directory
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# set envvar for XDG base dir support
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/X11/xinitrc"
export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"

export PATH="$PATH:$HOME/.local/bin"
export EDITOR="nvim"
export VISUAL="$EDITOR"

if [ ! "$DISPLAY" ] && [ "$XDG_VTNR" = 1 ]; then
    exec startx "$XINITRC"
fi
